version: "3.4"
services:
  docnet:
    build: .
    container_name: fil_rouge
    restart: always
    ports:
      - "1998:1998"
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=spring
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
