pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        SONARQUBE_SERVER = 'sonar-server'
        DOCKER_HUB_REPO = 'saidtalfana98/projet-fil-rouge'
        SONAR_TOKEN = credentials('sonar-credential')
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from the main branch
                git branch: 'main', url: 'https://github.com/saidtalfana/projet-fil-Rouge.git'
            }
        }

        stage('Build and Unit Tests') {
            steps {
                dir('pro') {
                    // Clean, install dependencies, and run tests
                    bat "mvn clean install"
                    bat "mvn test"
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                // Run SonarQube analysis
                withSonarQubeEnv(sonar-server) {
                    bat "mvn sonar:sonar -Dsonar.projectKey=pro_services -Dsonar.host.url=http://localhost:9000 -Dsonar.token=${SONAR_TOKEN}"
                }
            }
        }

        stage('Quality Gate Check') {
            steps {
                // Wait for SonarQube Quality Gate results
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                dir('pro') {
                    // Build the Docker image
                    script {
                        try {
                            bat "docker build -t pro-service-image ."
                        } catch (Exception e) {
                            error "Docker build failed: ${e.message}"
                        }
                    }
                }
            }
        }

        stage('Tag and Push Docker Images') {
            steps {
                script {
                    // Tag the image with the build number
                    def dockerTag = "${env.BUILD_NUMBER}"
                    docker.withRegistry("https://index.docker.io/v1/", 'docker-hub-credential') {
                        bat """
                            docker tag pro-service-image:latest ${DOCKER_HUB_REPO}:${dockerTag}
                            docker push ${DOCKER_HUB_REPO}:${dockerTag}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            // Clean the workspace after the build
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
